### ISSUE TITLE
Error in GameObjectBrush.cs

### ISSUE THREAD

**Issue by yibidaiguo** [skner-dev/DualGrid#1]
Dear author,
I'm writing to report an issue that I've encountered while using your project. I got the following error message:
Library\PackageCache\com.unity.2d.tilemap.extras@4.0.2\Editor\Brushes\GameObjectBrush\GameObjectBrush.cs(756,30): error CS0115: 'GameObjectBrushEditor.shouldSaveBrushForSelection': no suitable method found to override
I've double-checked the code in the specified location, and it seems that there might be something wrong with the method override implementation. It's preventing me from proceeding smoothly with my work related to this part of the code.
I hope you can take a look at this issue as soon as possible and provide a solution or some guidance on how to fix it. Thanks a lot for your hard work on this project and I'm looking forward to your reply.
Best regards,

**Comment by skner-dev** [comment]
Hi,

That error seems to be coming from the _Unity 2D Tilemap Extras_ package, so it's unrelated with the code for the Dual Grid.

I suggest you checking if you have the dependencies for _Unity 2D Tilemap Extras_ installed, my first guess would be at least one is missing from your project.

Cheers

**Comment by yibidaiguo** [comment]
Dear author,
I'm using Unity version 2022.3 and the version of Unity 2D Tilemap Extras is 3.1.2. After I downloaded your project from the Unity Package Manager, the following problem occurred. I checked the version of Unity 2D Tilemap Extras after the download and found that it contained both version 3.1.2 and version 4.0.2. Logically, there shouldn't be any problems, but the above error still appeared.
Later, instead of downloading this package from the Package Manager, I directly added the code into my project. After making adjustments, the error no longer showed up. I would like to ask you whether there will be any hidden dangers in doing so, because my version of Unity 2D Tilemap Extras is 3.1.2.
I'm looking forward to your reply.
Thank you!
Best regards,

**Comment by skner-dev** [comment]
I've managed to replicate the issue.

This package was instructing Unity that the minimum version for Unity 2D Tilemap Extras would be 4.0.2. But this version is not very compatible with previous Unity versions (I only tested until 2023.1+).

However, this dependency can actually be downgraded to version 3.1.2, which is the one used by Unity 2022.1+. I've updated the package manifest under commit 2053e3b1c07f1588908b486716e9b501c83b4994.

It seems to have worked in my end. Let me know if it resolves your issue.

Thanks

**Comment by yibidaiguo** [comment]
Dear author,
I would like to express my sincere gratitude for your patient guidance and timely updates. My issue has been successfully resolved.
Thank you very much.

**Comment by yibidaiguo** [comment]
I've reviewed your code and I think that making a slight adjustment to the&nbsp;HandleTilemapChange&nbsp;method in the&nbsp;DualGridTilemapModule&nbsp;class could lead to better results. The code is shown below:
private DualGridRuleTile Tile;
&nbsp;internal void HandleTilemapChange(Tilemap tilemap, Tilemap.SyncTile[] tileChanges)
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (tilemap == DataTilemap)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Undo.RecordObject(RenderTilemap, $"Updated {tileChanges.Length} render tile(s)");


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; foreach (Tilemap.SyncTile tileChange in tileChanges)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
		&nbsp; &nbsp;&nbsp;// Update the DualGridRuleTile of the tile in RendererTilemap before updating RendererTilemap
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Tile = (DualGridRuleTile)tileChange.tile;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; UpdateRenderTilemapFromDataTile(tileChange.position);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; }
These are just my humble opinions and I hope they can be helpful to you.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "skner-dev/DualGrid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月14日(星期四) 晚上9:08
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [skner-dev/DualGrid] Error in GameObjectBrush.cs (Issue #1)





 
I've managed to replicate the issue.
 
This package was instructing Unity that the minimum version for Unity 2D Tilemap Extras would be 4.0.2. But this version is not very compatible with previous Unity versions (I only tested until 2023.1+).
 
However, this dependency can actually be downgraded to version 3.1.2, which is the one used by Unity 2022.1+. I've updated the package manifest under commit 2053e3b.
 
It seems to have worked in my end. Let me know if it resolves your issue.
 
Thanks
